'use client'

import localFont from "next/font/local";
import "./globals.css";
import { MenuContext } from "@/contexts/MenuContext";
import { useState } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [menu, setMenu] = useState<boolean>(false)


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MenuContext.Provider value={{menu, setMenu}}>
          {children}
        </MenuContext.Provider>
        
      </body>
    </html>
  );
}
